# mysql listening on port 3306
# redis listening on port 6379
# service-end listening on port 8080
redis:
  image: redis
  volumes:
    - /server/data/redis:/data/

mysql:
  image: mysql:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=root
  volumes:
    - /server/data/mysql:/var/lib/mysql

service-end:
  image: xiaxzh/script
  links:
    - redis
    - mysql
  ports:
    - "8080:8080"